services:
  - type: web
    name: sic-result-viewer
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
